### ISSUE TITLE
User should be able to see if the image has wrong format

### ISSUE THREAD

**Issue by PurplePegasuss** [PictureInspector/Picture-Inspector#1]
Please add check for wrong image format. User should be notified in case of sending wrong picture format (for example GIFS, stickers, etc.).

**Comment by datapaf** [comment]
Hi! In the recent release, our team fixed the issue with handling the messages with wrong image format. Now the bot is going to ask you to send it an image in case the user sent something else. Thank you for the feedback, we really appreciate it!
